Umurinzi/Umurinzi/urls.py
from django.contrib import admin
from django.urls import path, include
import webapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls'))
]

Umurinzi/webapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

urlpatterns = [
    path("", home, name="user_home"),
    path("login", LoginView.as_view(template_name='webapp/login.html'), name="login"),
    path("logout",LogoutView.as_view(), name="logout"),
    path("signup", signup, name="signup"),
    path("item/<int:item_id>", itemDetail, name="item_details"),
    path("registeritem", registerItem, name="register_new_item"),
    path("manageitems", manageItems, name="manage_item"),
    path("reportfound", registerFoundItem, name="register_found_item"),
    path("get_categories/", get_categories, name='get_categories'),
    path("filter/<int:category>/<int:subcategory>/", itemFilter, name="filter_items"),
    path("items/", retrieveItems, name="items"),
    path("registereditems/", retrieveRegisteredItems, name="registered_items"),
    path("itemsearch/", searchItem, name="item_serach"),
    path("item/report/<int:item_id>", report_item, name="item_report"),
    path("item/delete/<int:item_id>", delete_item, name="item_delete"),
    path("item/update/<int:item_id>", update_item, name="item_update"),
    path("claimitem/<int:item_id>", claim_item, name="claim_item"),
    path('validateitem/', validateItem, name='validate_item'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Umurinzi/webapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
    

class CustomUserManager(BaseUserManager):
    """ Model for custom User Manager"""
    def create_user(self,user_id, password=None, **extra_fields):
        """ create user
            args:
                user_id: user id
                password: user password
                extra fields: more options
            return:
                user instance
        """
        user = self.model(user_id=user_id, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, user_id, password=None, **extra_fields):
        """ create superuser
            args:
                user_id: user id
                password: user password
                extra fields: more options
            return:
                create_user(user_id, password, **extra_fields)
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(user_id, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """ Model for custom User"""
    user_id = models.CharField(max_length=20, unique=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = "user_id"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()


class UserProfile(models.Model):
    """ Model for Userprofile"""
    user_id = models.ForeignKey('User', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, null=True)
    tel_no = models.CharField(max_length=12)

    def __str__(self)->str:
        """ Model string representation"""
        return (self.first_name +" "+ self.last_name)

    def get_short_name(self)->str:
        """ get user short name"""
        return (self.first_name)

      
class Item(models.Model):
    """ Model for Item"""
    brand_choices = [('SAMSUNG', 'SAMSUNG'),('TECNO','TECNO'), ('IPHONE','IPHONE'), ('HP', 'HP'), ('ITEL','ITEL'), ('OTHER', 'OTHER')]
    status_choice = [("OWN", "Own"), ('LOST', 'Lost'), ('FOUND', 'Found'), ('STOLEN', 'Stolen'), ('PENDING', 'Pending'), ('DELETED', 'Deleted')]

    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    category = models.ForeignKey("ItemCategory", on_delete=models.DO_NOTHING)
    sub_category = models.ForeignKey("SubCategory", on_delete=models.DO_NOTHING)
    brand = models.CharField(max_length=100, choices=brand_choices)
    status = models.CharField(max_length=10, choices=status_choice)
    owner = models.ForeignKey("User", on_delete=models.CASCADE, null=True) 

    def __str__(self) -> str:
        """ Model string representation"""
        return self.name
   

class Image(models.Model):
    """ Model for Item Images"""
    item_id = models.ForeignKey("Item", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')

    def __str__(self) -> str:
        """ Model string representation"""
        return str(self.image)
    
class SpecialId(models.Model):
    """ Model for Item identifying numbers"""
    types = [("SN", "Serial Number"),
             ("IMEI", "IMEI"),
             ("CN", "Card Number"),
             ("MAC", "MAC Address")
            ]
    item_id = models.ForeignKey("Item", on_delete=models.CASCADE) 
    number_type = models.CharField(max_length=100, choices=types)
    number_value = models.CharField(max_length=100)

    def __str__(self) -> str:
        """ Model string replesantation"""
        return self.item_id.name + ' ' +self.number_type

class ItemCategory(models.Model):
    """ Model for Item Category"""
    category_name = models.CharField(max_length=100)

    def __str__(self) -> str:
        """ Model string replesantation"""
        return self.category_name

class SubCategory(models.Model):
    """ Model for Item Subcategory"""
    category = models.ForeignKey("ItemCategory", on_delete=models.CASCADE)
    sub_category = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self) -> str:
        """ Model string replesantation"""
        return self.sub_category


class Report(models.Model):
    """ Model for reported Items"""
    item_id = models.ForeignKey("Item", on_delete=models.CASCADE, null=True, blank=True)
    province = models.CharField(max_length=20, null=True, blank=False)
    district = models.CharField(max_length=20, null=True, blank=True)
    sector = models.CharField(max_length=20, null=True, blank=True)
    report_time = models.DateTimeField()

    def __str__(self) -> str:
        """ Model string representation"""
        return self.item_id.name

Umurinzi/webapp/forms.py
from django.forms.models import inlineformset_factory
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *

class Signup_form(UserCreationForm):
    first_name  = forms.CharField(label="", min_length=2)
    last_name   = forms.CharField(label="", required=False)
    tel_no      = forms.CharField(label="", min_length=10, max_length=12)
    user_id     = forms.CharField(label="", min_length=16, max_length=16)
    class Meta(UserCreationForm):
        model   = User
        fields  = ["user_id", "first_name", "last_name", "tel_no"]


class SpecialIDForm(forms.ModelForm):
    number_value      = forms.CharField(label="", widget=forms.TextInput(attrs={"placeholder":"Number"}))
    class Meta:
        model = SpecialId
        fields = ['number_type', 'number_value']

SpecialId_set = forms.modelformset_factory(SpecialId, form=SpecialIDForm, extra=3, max_num=3)
updateId_set = forms.modelformset_factory(SpecialId, form=SpecialIDForm, extra=3, max_num=3, validate_max=False, validate_min=False, can_delete=True)

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["image"]

Image_set = forms.modelformset_factory(Image, fields=["image"], extra=3, max_num=3)
updateImage_set = forms.modelformset_factory(Image, fields=["image"], extra=3, max_num=3, validate_max=False, validate_min=False, can_delete=True)

class UserRegisterItem(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["name", "description", "category", "sub_category", "brand" ]

class UserFoundItem(forms.ModelForm):
    province = forms.CharField(label="", max_length=50, widget=forms.Select(), required=True)
    sector   = forms.CharField(label="", max_length=50, widget=forms.Select(), required=True)
    district = forms.CharField(label="", max_length=50, widget=forms.Select(), required=True)
    date_time_field = forms.DateTimeField(widget=forms.DateTimeInput(attrs={"type":"datetime-local"}))
    class Meta:
        model = Item
        fields = ["name", "description", "category", "sub_category", "brand", "province", "district", "sector", "date_time_field" ]

class ValidateItem(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["name", "category", "sub_category", "brand"]

Umurinzi/webapp/templates/webapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}" />
    <script src="{% static 'webapp/js/jquery.js'%}"></script>
    <link
      rel="stylesheet"
      href="{% static 'webapp/bootstrap/css/bootstrap.min.css' %}"
    />
    <script src="{% static 'webapp/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    {% block link %}{% endblock %}
    <!-- <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script> -->

    <title>UMURINZI</title>
  </head>
  <body>
    {% block header %}
    <header>
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img
              src="{% static 'webapp/assets/logo3.jpeg' %}"
              alt="Logo"
              width="30"
              height="30"
              class="d-inline-block align-text-top"
            />
            UMURINZI
          </a>
          {% if user.is_authenticated %}
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'user_home' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'manage_item' %}"
                >Manage Item</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'validate_item' %}"
                >Validate Item</a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                >Register</a
              >
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{% url 'register_new_item'%}"
                    >New item</a
                  >
                </li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{% url 'register_found_item' %}"
                    >Found item</a
                  >
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'logout' %}"
                >Logout</a
              >
            </li>
          </ul>
          {% else %}
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'user_home' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'validate_item'%}"
                >Validate Item</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
          </ul>
          {% endif %}
        </div>
      </nav>
    </header>
    {% endblock %} {% block main %}
    <main>
      {% block search %}
      <div class="pt-2">
        <form
          id="search-form"
          class="d-sm-flex justify-content-center"
          role="search"
          method="post"
        >
          {% csrf_token %}
          <input
            id="search-input"
            class="form-control me-2"
            type="search"
            placeholder="Search.."
            aria-label="Search"
          />
          <button class="btn btn-primary btn-sm" type="submit">Search</button>
        </form>
      </div>
      {% endblock %}
      <div id="main-content" class="d-flex justify-content-between">
        {% block sidebar %} {% endblock %} {% block content %} {% endblock %}
      </div>
    </main>
    {% endblock %} {% block footer %}
    <footer>
      <p class="text-primary text-center">
        © Lost And Found, All Right Reserved.
      </p>
    </footer>
    {% endblock %}
  </body>
</html>

Umurinzi/webapp/templates/webapp/index.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/home.css'%}" />
<script src="{% static 'webapp/js/main.js'%}"></script>
{% endblock %} {% block sidebar %}
<div id="sidebar" class="sidebar">
  <h3>Categories</h3>
  <ul class="category-list"></ul>
</div>
{% endblock %} {% block content %}
<div
  id="content"
  class="content d-flex flex-wrap justify-content-around align-self-start"
></div>
{% endblock %}

Umurinzi/webapp/templates/webapp/itemView.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/report.css'%}" />
<script type="module" src="{% static 'webapp/js/location.js'%}"></script>
<script type="module" src="{% static 'webapp/js/model.js'%}"></script>
{% endblock %} {% block main%}
<main>
  <h2 class="mb-12 text-2xl text-center">Item Details</h2>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div id="demo" class="carousel slide" data-bs-ride="carousel">
          <!-- Indicators/dots -->
          <div class="carousel-indicators">
            <button
              type="button"
              data-bs-target="#demo"
              data-bs-slide-to="0"
              class="active"
            ></button>
            <button
              type="button"
              data-bs-target="#demo"
              data-bs-slide-to="1"
            ></button>
            <button
              type="button"
              data-bs-target="#demo"
              data-bs-slide-to="2"
            ></button>
          </div>

          <!-- The slideshow/carousel -->
          <div class="carousel-inner">
            {% for image in images %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img
                src="{{ image.image.url }}"
                class="d-block w-50"
                alt="item image"
              />
            </div>
            {% endfor %}
          </div>

          <!-- Left and right controls/icons -->
          <button
            class="carousel-control-prev"
            type="button"
            data-bs-target="#demo"
            data-bs-slide="prev"
          >
            <span class="carousel-control-prev-icon"></span>
          </button>
          <button
            class="carousel-control-next"
            type="button"
            data-bs-target="#demo"
            data-bs-slide="next"
          >
            <span class="carousel-control-next-icon"></span>
          </button>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="item-info">
          <h2 class="mb-12 text-2xl text-center">{{ item.name }}</h2>
          <p>{{ item.description }}</p>
          <p>Category: {{ item.category }}</p>
          <p>Location: {{ item.sub_category }}</p>
          <p>Brand : {{ item.brand }}</p>
          <p>Status : {{ item.status }}</p>
        </div>
        <div class="item-options d-flex justify-content-around">
          {% if item.owner == request.user %}
          <div>
            <!-- Button trigger modal -->
            <button
              id="report-btn"
              type="button"
              class="btn btn-primary"
              data-bs-toggle="modal"
              data-bs-target="#report-modal"
            >
              Report
            </button>

            <!-- Modal -->
            <div
              class="modal fade"
              id="report-modal"
              data-bs-backdrop="static"
              data-bs-keyboard="false"
              tabindex="-1"
              aria-labelledby="staticBackdropLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">
                      Report Item
                    </h1>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    ></button>
                  </div>
                  <div class="modal-body">
                    <form
                      id="report-form"
                      action="{% url 'item_report' item_id=item.id%}"
                      method="post"
                    >
                      {% csrf_token%}
                      <select name="status" id="status">
                        <option value="">select item status</option>
                        <option value="LOST">Lost</option>
                        <option value="STOLEN">Stolen</option>
                      </select>
                      <select
                        name="province"
                        maxlength="50"
                        id="id_province"
                      ></select>
                      <select
                        name="district"
                        maxlength="50"
                        id="id_district"
                      ></select>
                      <select
                        name="sector"
                        maxlength="50"
                        id="id_sector"
                      ></select>
                      <p>
                        <label for="id_date_time_field">Date time field:</label>
                        <input
                          type="datetime-local"
                          name="date_time_field"
                          required=""
                          id="id_date_time_field"
                        />
                      </p>
                    </form>
                  </div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-bs-dismiss="modal"
                    >
                      Cancel
                    </button>
                    <button
                      id="report-form-btn"
                      type="submit"
                      class="btn btn-danger"
                    >
                      Report
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <!-- Button trigger modal -->
            <button
              type="button"
              class="btn btn-primary"
              data-bs-toggle="modal"
              data-bs-target="#update-modal"
            >
              Update
            </button>

            <!-- Modal -->
            <div
              class="modal fade"
              id="update-modal"
              data-bs-backdrop="static"
              data-bs-keyboard="false"
              tabindex="-1"
              aria-labelledby="staticBackdropLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">
                      Update Item
                    </h1>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    ></button>
                  </div>
                  <div class="modal-body">Update item: {{item.name}}</div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-bs-dismiss="modal"
                    >
                      Cancel
                    </button>
                    <a href="{% url 'item_update' item_id=item.id%}"
                      ><button type="button" class="btn btn-danger">
                        Update
                      </button></a
                    >
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <!-- Button trigger modal -->
            <button
              type="button"
              class="btn btn-primary"
              data-bs-toggle="modal"
              data-bs-target="#delete-modal"
            >
              Delete
            </button>

            <!-- Modal -->
            <div
              class="modal fade"
              id="delete-modal"
              data-bs-backdrop="static"
              data-bs-keyboard="false"
              tabindex="-1"
              aria-labelledby="staticBackdropLabel"
              aria-hidden="true"
            >
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">
                      Item Detail
                    </h1>
                    <button
                      type="button"
                      class="btn-close"
                      data-bs-dismiss="modal"
                      aria-label="Close"
                    ></button>
                  </div>
                  <div class="modal-body">
                    <h3>Confirm deletion of: {{item.name}}</h3>
                  </div>
                  <div class="modal-footer">
                    <button
                      type="button"
                      class="btn btn-secondary"
                      data-bs-dismiss="modal"
                    >
                      Cancel
                    </button>
                    <a href="{% url 'item_delete' item_id=item.id%}"
                      ><button type="button" class="btn btn-danger">
                        Delete
                      </button></a
                    >
                  </div>
                </div>
              </div>
            </div>
          </div>
          {%else%}
          <!-- Button trigger modal -->
          <button
            id="claim-form-btn"
            type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target=""
            data-item-id="{{ item.id }}"
          >
            Claim Item
          </button>

          <!-- Modal -->
          <div
            class="modal fade"
            id="staticBackdrop"
            data-bs-backdrop="static"
            data-bs-keyboard="false"
            tabindex="-1"
            aria-labelledby="staticBackdropLabel"
            aria-hidden="true"
          >
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="staticBackdropLabel">
                    Claim Detail
                  </h1>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div id="claim-body" class="modal-body">
                  You are not allowed to claim item
                </div>
                <div class="modal-footer">
                  <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal"
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
          {%endif%}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

Umurinzi/webapp/templates/webapp/login.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/signup.css'%}" />
<script src="{% static 'webapp/js/form.js'%}"></script>
{% endblock %} {%block main %}
<main>
  <div
    id="login-form"
    class="container-fluid p-0 d-flex flex-column justify-content-center align-items-center"
  >
    <form class="border p-5" action="" method="post">
      <h2 id="form-title">LOGIN</h2>
      {% csrf_token %}
      <label for="user_id" class="form-label d-block">National ID Number</label
      >{{form.username}}
      <label for="password" class="form-label d-block">Password</label>
      {{form.password}}
      <button class="btn btn-primary mt-4 mb-2">LOGIN</button>
      <p>Don't have an account? <a href="./signup.html">Click here</a></p>
    </form>
  </div>
</main>
{% endblock %}

Umurinzi/webapp/templates/webapp/manageItem.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/home.css'%}" />
<script src="{% static 'webapp/js/manage.js'%}"></script>
{% endblock %} {% block sidebar %}
<div id="sidebar" class="sidebar">
  <h3>Categories</h3>
  <ul class="category-list"></ul>
</div>
{% endblock %} {% block content %}
<div
  id="content"
  class="content d-flex flex-wrap justify-content-around align-self-start"
></div>
{% endblock %}

Umurinzi/webapp/templates/webapp/registerFoundItem.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/signup.css'%}" />
<script type="module" src="{% static 'webapp/js/location.js'%}"></script>
{% endblock %} {% block main %}
<main>
  <div class="container-fluid p-0 d-flex justify-content-center">
    <form
      class="border p-5"
      action=""
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token%}
      <h3>Report Found Item</h3>
      {{form.as_p}} {{id_form.as_p}} {{image_form.as_p}}
      <button class="btn btn-primary mt-2">Submit</button>
    </form>
  </div>
</main>
{% endblock %}

Umurinzi/webapp/templates/webapp/registerNewItem.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/signup.css'%}" />
{% endblock %} {% block main %}
<main>
  <div class="container-fluid p-0 d-flex justify-content-center">
    <form
      class="border p-5"
      action=""
      enctype="multipart/form-data"
      method="post"
    >
      {%csrf_token%}
      <h3>Register New Item</h3>
      {{form.as_p}} {{id_form.as_p}} {{image_form.as_p}}
      <button class="btn btn-primary mt-2">Submit</button>
    </form>
  </div>
</main>
{% endblock %}

Umurinzi/webapp/templates/webapp/signup.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/signup.css'%}" />
{% endblock %} {%block main %}
<main>
  <div class="container-fluid p-0 d-flex justify-content-center mt-2">
    <form id="signup-form" class="border p-5 w-50" action="" method="post">
      <h2 id="form-title">SIGNUP</h2>
      {% csrf_token %}
      <label for="user_id" class="form-label d-block">National ID Number</label
      >{{form.user_id}}
      <label for="first_name" class="form-label d-block">First Name</label>
      {{form.first_name}}
      <label for="last_name" class="form-label d-block">Last Name</label>
      {{form.last_name}}
      <label for="tel_no" class="form-label d-block">Telephone Number</label>
      {{form.tel_no}}
      <label for="password1" class="form-label d-block">Password</label>
      {{form.password1}}
      <label for="password2" class="form-label d-block">Confirm Password</label>
      {{form.password2}}
      <button
        id="signup-btn"
        class="btn btn-primary mt-3 mb-2 d-block"
        type="submit"
      >
        Submit
      </button>
      <p>Aleady have an account? <a href="{% url 'login' %}">Click here</a></p>
    </form>
  </div>
</main>
{% endblock %}

Umurinzi/webapp/templates/webapp/updateItem.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/report.css'%}" />
{% endblock %} {% block main %}
<main>
  <div class="container-fluid p-0 d-flex justify-content-center mb-5">
    <div class="search-container bg-light">
      <h2 class="text-primary">REGISTER ITEM</h2>
    </div>
  </div>
  <div class="container-fluid p-0 d-flex justify-content-center">
    <form
      class="border p-5"
      action=""
      enctype="multipart/form-data"
      method="post"
    >
      {%csrf_token%}
      <h3>REGISTER ITEM</h3>
      {{form.as_p}} {{id_form.as_p}} {{image_form.as_p}}
      <button class="btn btn-primary mt-2">Submit</button>
    </form>
  </div>
</main>
{% endblock %}

Umurinzi/webapp/templates/webapp/userHome.html
{% extends "webapp/base.html" %} {% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'webapp/css/home.css'%}" />
<script src="{% static 'webapp/js/main.js'%}"></script>
{% endblock %} {% block sidebar %}
<div id="sidebar" class="sidebar">
  <h3>Categories</h3>
  <ul class="category-list"></ul>
</div>
{% endblock %} {% block content %}
<div id="content" class="content"></div>
{% endblock %}